### ISSUE TITLE
can't use it with tabbar

### ISSUE THREAD

**Issue by junaidgoharhashmi** [rod90ad/sliverbar_with_card#1]
i am using defaulttabbar in body of cardsliverappbar but when list in tab scroll then cardsliverappbar not move as sliverappbar behavoiur. how can i achieve it?

**Comment by rod90ad** [comment]
i think this will not work because you have a scroll inside the DefaultTabBar and it will scroll, if you see the code the body of SliverAppBarWithCard can't handle a vertical scroll inside it because he need to user you internal scroll to controll all the animations. maybe you can stop de scroll of DefaultTabBar and it will work but i'm not sure of this.
